<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit user';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Username');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Password');

$firstname = $form->get('firstname');
$firstname->setAttribute('class', 'form-control');
$firstname->setAttribute('placeholder', 'Firstname');

$lastname = $form->get('lastname');
$lastname->setAttribute('class', 'form-control');
$lastname->setAttribute('placeholder', 'Lastname');

$admin = $form->get('admin');
$admin->setAttribute('class', 'form-control');
$admin->setAttribute('placeholder', 'Admin');

$clinic = $form->get('id_clinic');
$clinic->setAttribute('class', 'form-control');
$clinic->setAttribute('placeholder', 'Clinic');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($username) ?>
        <?= $this->formElement($username) ?>
        <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($password) ?>
        <?= $this->formElement($password) ?>
        <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($firstname) ?>
        <?= $this->formElement($firstname) ?>
        <?= $this->formElementErrors()->render($firstname, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($lastname) ?>
        <?= $this->formElement($lastname) ?>
        <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($admin) ?>
        <?= $this->formElement($admin) ?>
        <?= $this->formElementErrors()->render($admin, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($clinic) ?>
        <?= $this->formElement($clinic) ?>
        <?= $this->formElementErrors()->render($clinic, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();