<?php
$title = 'Login';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Username');

// This provides a default CSS class and placeholder text for the artist element:
$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'welcome']));
$form->prepare();

echo $this->form()->openTag($form);
?>

    <div class="container">
        <div class="row">
            <div class="col-md-5 shadow-sm">
                <h3 class="mb-3 pt-2 text-md-center">
                    <?= $this->escapeHtml($this->translate('Log into your account')); ?>
                </h3>
                <?= $this->form()->openTag($form); ?>
                <span class="form-text text-muted pb-2">
                    <?= sprintf(
                        $this->translate('Dont have an account? %sSign up%s.'),
                        '<a href="signup">', '</a>'
                    ); ?>
                </span>

                <div class="mb-3">
                    <?= $this->formLabel($form->get('username')); ?>
                    <div class="form-group">
                        <?= $this->formText($form->get('username')); ?>
                    </div>
                    <div class="text-danger">
                        <?= $this->formElementErrors($form->get('username')); ?>
                    </div>
                </div>
                <div class="mb-3">
                    <?= $this->formLabel($form->get('password')); ?>
                    <div class="form-group">
                        <?= $this->formText($form->get('password')); ?>
                    </div>
                    <div class="text-danger">
                        <?= $this->formElementErrors($form->get('password')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();